require:
  - standard
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

Layout/LineLength:
  Max: 80

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*

Performance:
  Enabled: true
RSpec:
  Enabled: true
RSpec/DescribeClass:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false